CREATE DATABASE IF NOT EXISTS gallery;
USE gallery;

CREATE TABLE IF NOT EXISTS cover (
    id INT AUTO_INCREMENT PRIMARY KEY,
    coverName VARCHAR(255) NOT NULL,
    coverOrder INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    imgName VARCHAR(255) NOT NULL,
    orderImg INT NOT NULL,
    datename VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
